### ISSUE TITLE
Dumping to JSON does not escape strings

### ISSUE THREAD

**Issue by jjaraalm** [epics-base/pvaPy#74] opened 2022-01-16 14:54 UTC
`PvObject.toJSON()` does not properly escape strings which can result in malformed JSON. For example,

```python
>>> pva.PvObject({'foo': pva.STRING}, {'foo': '"bar"'}).toJSON(True)
'{\n "foo": ""bar""\n}'
```
This cannot be loaded by e.g., `json.loads`. The correct output is
```python
>>> json.dumps({'foo': '"bar"'})
'{"foo": "\\"bar\\""}'
```

**Comment by sveseli** [comment] 2022-01-17 04:53
The problem is in the underlying epics pvdata library. Until it gets fixed, you can use this as a workaround:

<pre>
>>> pv = PvObject({'foo': STRING}, {'foo': '"bar"'})
>>> s = json.dumps(pv.toDict())
>>> s
'{"foo": "\\"bar\\""}'
>>> json.loads(s)
{'foo': '"bar"'}
>>> 
</pre>

**Comment by jjaraalm** [comment] 2022-01-17 18:01
Yup, that's what I'm doing. Just wanted to open this in case others run into the same problem.

**Comment by sveseli** [comment] 2022-01-18 15:57
The underlying issue in pvDataCPP has been created (see https://github.com/epics-base/pvDataCPP/issues/78).

**Comment by sveseli** [comment] 2022-11-14 16:43
This has been fixed in pvDataCPP.

**Closed as completed by sveseli** 2022-11-14 16:43 UTC
